### ISSUE TITLE
A puzzle about seq in CRDTInterface

### ISSUE THREAD

**Issue by yz1509** [JYwellin/CRDT-TLA#2]
https://github.com/JYwellin/CRDT-TLA/blob/842b82337c7d328457d527788aff162b96322208/CRDTInterface.tla#L7

Why seq incremented upon `IntDo` and `IntSend` instead of `IntDo` ?

**Comment by JYwellin** [comment]
Because in spec like **StateAWSet**, if **seq** dosen't increment upon **IntSend**, one node may send two messages with the same content,  so there is conflict with the uniqueness of message in the communication layer. For more details, you can read [http://www.jos.org.cn/1000-9825/ 0000.htm](url).

**Comment by JYwellin** [comment]
Because in spec like **StateAWSet**, if **seq** dosen't increment upon **IntSend**, one node may send two messages with the same content, so there is conflict with the uniqueness of message in the communication layer. For more details, you can read http://www.jos.org.cn/jos/ch/reader/create_pdf.aspx?file_no=5956&year_id=2020&quarter_id=5&falg=1.

**Comment by yz1509** [comment]
Thanks for your reply. 
**Send** is ready all the time rather than after the state changes. seem to understand, thx again.
